name: Continuous Integration
on: [push]
jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['12', '14', '16', '17']
    name: Run tests with nodejs ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: run tests
        run: |
          npm ci
          npx concurrently -r 'npx tsetse' 'npx jest'
